import { defineEventHandler } from "h3";

export default defineEventHandler(() => [
	{
		name: "Spartan UI",
		imageSrc: "/images/projects/spartan-ui.jpg",
		url: "https://www.spartan.ng",
		category: "Open Source",
		version: "17.3.0",
		versionGroup: "v15 and up",
		analogVersion: "1.2.2",
		uiLib: "Spartan UI, Tailwind CSS",
		pricing: "Free",
		threeD: false,
		developer: "Robin Goetz",
	},
	{
		name: "AngleBrackets",
		imageSrc: "/images/projects/anglebrackets.jpg",
		url: "https://anglebrackets.dev",
		category: "Personal Website",
		version: "17.3.0",
		versionGroup: "v15 and up",
		analogVersion: "1.3.1",
		uiLib: "None",
		pricing: "Free",
		threeD: false,
		developer: "Duncan Faulkner",
	},
	{
		name: "Angular Macedonia",
		imageSrc: "/images/projects/angular-macedonia.jpg",
		url: "https://www.angularmacedonia.org",
		category: "Community",
		version: "17.2.0",
		versionGroup: "v15 and up",
		analogVersion: "0.2.0",
		uiLib: "Tailwind CSS",
		pricing: "Free",
		threeD: false,
		developer: "Angular Macedonia",
	},
	{
		name: "MrRobot",
		imageSrc: "/images/projects/mrrobot.jpg",
		url: "https://mrrobot.dev",
		category: "Personal Website",
		version: "17.3.2",
		versionGroup: "v15 and up",
		analogVersion: "1.2.0",
		uiLib: "Tailwind CSS",
		pricing: "Free",
		threeD: false,
		developer: "Luis Castro",
	},
	{
		name: "AnguHashBlog",
		imageSrc: "/images/projects/analog-material-anguhashblog.jpg",
		url: "https://analogmaterial.anguhashblog.com/",
		category: "Open Source",
		version: "17.3.0",
		versionGroup: "v15 and up",
		analogVersion: "1.2.0",
		uiLib: "None",
		pricing: "Free",
		threeD: false,
		developer: "Esther White",
	},
	{
		name: "Angular HUB",
		imageSrc: "/images/projects/angular-hub.jpg",
		url: "https://angular-hub.com",
		category: "Community",
		version: "18.0.0",
		versionGroup: "v15 and up",
		analogVersion: "1.4.0",
		uiLib: "PrimeNG, Tailwind CSS",
		pricing: "Free",
		threeD: false,
		developer: "Gerome Grignon",
	},
	{
		name: "PDFun",
		imageSrc: "/images/projects/pdfun.jpg",
		url: "https://pdfun.xyz",
		category: "Open Source",
		version: "18.0.0",
		versionGroup: "v15 and up",
		analogVersion: "1.3.1",
		uiLib: "PrimeNG, Tailwind CSS",
		pricing: "Free",
		threeD: false,
		developer: "Dale Nguyen",
	},
	{
		name: "Angular Belgrade",
		imageSrc: "/images/projects/angular-belgrade.jpg",
		url: "https://angularbelgrade.org",
		category: "Community",
		version: "16.2.2",
		versionGroup: "v15 and up",
		analogVersion: "0.2.0",
		uiLib: "None",
		pricing: "Free",
		threeD: false,
		developer: "Angular Belgrade",
	},
	{
		name: "Downloads Tracker",
		imageSrc: "/images/projects/angular-download-tracker.jpg",
		url: "https://angular-download-tracker.vercel.app/",
		category: "Productivity",
		version: "17.3.5",
		versionGroup: "v15 and up",
		analogVersion: "1.2.0",
		uiLib: "None",
		pricing: "Free",
		threeD: false,
		developer: "Kevin",
	},
	{
		name: "Monorepo X",
		imageSrc: "/images/projects/monorepox.jpg",
		url: "https://monorepox.com/workshop",
		category: "Personal Website",
		version: "16.2.11",
		versionGroup: "v15 and up",
		analogVersion: "1.2.0",
		uiLib: "PrimeNG, Tailwind CSS",
		pricing: "Free",
		threeD: false,
		developer: "Stefan Haas",
	},
	{
		name: "Hapax Legomenon",
		imageSrc: "/images/projects/hapax-legomenon.jpg",
		url: "https://elanna.me/",
		category: "Personal Website",
		version: "17.0.5",
		versionGroup: "v15 and up",
		analogVersion: "1.2.0",
		uiLib: "Tailwind CSS",
		pricing: "Free",
		threeD: false,
		developer: "Elanna Grossman",
	},
	{
		name: "Tuzuper",
		imageSrc: "/images/projects/tuzuper.jpg",
		url: "https://elanna.me/",
		category: "Shopping",
		version: "17.3.5",
		versionGroup: "v15 and up",
		analogVersion: "1.2.0",
		uiLib: "Tailwind CSS",
		pricing: "Free",
		threeD: false,
		developer: "El_vlad99",
	},
	{
		name: "Jay Bell",
		imageSrc: "/images/projects/jaybell.jpg",
		url: "https://jaybell.me/",
		category: "Personal Website",
		version: "17.3.5",
		versionGroup: "v15 and up",
		analogVersion: "1.2.0",
		uiLib: "Tailwind CSS",
		pricing: "Free",
		threeD: false,
		developer: "Jay Cooper Bell",
	},
	{
		name: "Open Plumbing",
		imageSrc: "/images/projects/open-plumbing.jpg",
		url: "https://open.plumbing/",
		category: "Company Website",
		version: "18.0.3",
		versionGroup: "v15 and up",
		analogVersion: "1.2.0",
		uiLib: "Tailwind CSS",
		pricing: "Free",
		threeD: false,
		developer: "Ryann",
	},
	{
		name: "NG Rome",
		imageSrc: "/images/projects/ngrome.jpg",
		url: "https://ngrome.io/",
		category: "Company Website",
		version: "18.0.0",
		versionGroup: "v15 and up",
		analogVersion: "1.2.0",
		uiLib: "Tailwind CSS",
		pricing: "Free",
		threeD: false,
		developer: "NG Rome",
	},
 	{
		name: "Pierre's Portfolio",
		imageSrc: "/images/projects/pbouillon.jpg",
		url: "https://pbouillon.github.io",
		category: "Personal Website",
		version: "18.0.0",
		versionGroup: "v15 and up",
		analogVersion: "1.5.0",
		uiLib: "Tailwind CSS",
		pricing: "Free",
		threeD: false,
		developer: "Pierre Bouillon",
	},
]);
